
/*
 * Generated by Xtext/JEE6 Generator.
 * Copyright (C) 2013  itemis AG 
 * $Id$
 */

package org.jeegen.faces.entities;

import javax.persistence.Cacheable;
import javax.persistence.Entity;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * This class implements the Lock entity bean,
 */
@Entity
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@Table(name = "AtomicLock")
@Cacheable(false)
public class Lock extends AbstractLock
{
	private static final long serialVersionUID = 1L;

	/**
	 * This method is a transient getter of the virtual property info.
	 *
	 * @return The computed value for property info.
	 */
	@Transient
	@Override
	public String getInfo()
	{
		return String.format("Lock %s: %d", getCode(), getValue());
	}
}
