
/*
 * Generated by Xtext/JEE6 Generator.
 */

package de.itemis.faces.handler;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

@ManagedBean
@SessionScoped
public class InfoHandler extends AbstractInfoHandler {
	private static final long serialVersionUID = 1L;
}
