/*
 * generated by Xtext
 */
package org.jeegen.jee7;

import org.eclipse.xtext.linking.ILinkingDiagnosticMessageProvider;

import org.jeegen.jee7.formatting.Jee7LinkingDiagnosticMessageProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DslRuntimeModule extends org.jeegen.jee7.AbstractDslRuntimeModule
{
	public Class<? extends ILinkingDiagnosticMessageProvider> bindILinkingDiagnosticMessageProvider()
	{
		return Jee7LinkingDiagnosticMessageProvider.class;
	}
}
