/*
 * Generated by Xtext/JEE6 Generator.
 * $Id$
 */

package org.jeegen.faces.dao;

import javax.ejb.Stateless;

import org.jeegen.jee7.util.Profiled;

@Stateless
@Profiled
public class InfoDaoBean extends AbstractInfoDaoBean
{
}
