/*
* generated by Xtext
*/
package de.itemis.jee6;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return de.itemis.jee6.ui.internal.DslActivator.getInstance().getInjector("de.itemis.jee6.Dsl");
	}
	
}
