
/*
 * Generated by Xtext/JEE7 Generator.
 * Copyright (C) 2014  itemis AG 
 * $Id$
 */

package de.itemis.faces.beans;

import java.io.Serializable;
import java.util.logging.Logger;

import javax.enterprise.inject.Produces;
import javax.enterprise.inject.spi.InjectionPoint;

public class Producer extends AbstractProducer implements Serializable {
	private static final long serialVersionUID = 1L;

	@Produces
	@Override
	public Logger produceLogger(final InjectionPoint injector) {
		return Logger.getLogger(injector.getMember().getDeclaringClass()
				.getName());
	}
}
