/*
 * Generated by Xtext/JEE6 Generator.
 * $Id$
 */

package de.itemis.faces.dao;

import javax.ejb.Stateless;

import de.itemis.jee7.util.Profiled;

@Stateless
@Profiled
public class AdminDaoBean extends AbstractAdminDaoBean
{
}
