/*
 * generated by Xtext
 */
package org.jeegen.jee6;

import org.eclipse.xtext.linking.ILinkingDiagnosticMessageProvider;

import org.jeegen.jee6.formatting.Jee6LinkingDiagnosticMessageProvider;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DslRuntimeModule extends org.jeegen.jee6.AbstractDslRuntimeModule
{
	public Class<? extends ILinkingDiagnosticMessageProvider> bindILinkingDiagnosticMessageProvider()
	{
		return Jee6LinkingDiagnosticMessageProvider.class;
	}
}
