/*
 * generated by Xtext
 */
package de.itemis.jee6;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DslRuntimeModule extends de.itemis.jee6.AbstractDslRuntimeModule {

}
