
/*
 * Generated by Xtext/JEE6 Generator.
 * Copyright (C) 2012  itemis AG 
 * $Id$
 */

package org.jeegen.example.entities;

import javax.persistence.*;

/**
 * This class implements the Member entity bean,
 */
@Entity
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@Table(name = "Member")
@Cacheable
public class Member extends AbstractMember {
	private static final long serialVersionUID = 1L;

	/**
	 * This method is a transient getter of the virtual property name.
	 *
	 * @return The computed value for property name.
	 */
	@Transient
	@Override
	public String getName() {
		return String.format("%s,  %s", getLastname(), getFirstname());
	}
}
