
/*
 * Generated by Xtext/JEE6 Generator.
 * Copyright (C) 2015  Steffen A. Mork, Dominik Pieper 
 * $Id$
 */

package org.jeegen.jee6.dbauth.dao;

import javax.ejb.Stateless;
import javax.interceptor.Interceptors;
import javax.persistence.TypedQuery;

import org.jeegen.jee6.dbauth.entities.AuthInfo;
import org.jeegen.jee6.util.Profiler;

@Stateless
@Interceptors(Profiler.class)
public class UserDaoBean extends AbstractUserDaoBean
{
	public AuthInfo findAuthInfo(final String email)
	{
		TypedQuery<AuthInfo> query = em.createQuery("SELECT ai FROM AuthInfo ai WHERE ai.email = :email", AuthInfo.class);
		
		query.setParameter("email", email);
		
		return query.getSingleResult();
	}
}
