/*
* generated by Xtext
*/
package org.jeegen.jee7.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class DslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
