/*
* generated by Xtext
*/
package de.itemis.jee6.ui.contentassist;

import de.itemis.jee6.ui.contentassist.AbstractDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class DslProposalProvider extends AbstractDslProposalProvider {

}
