/*
 * Generated by Xtext/JEE7 Generator.
 * Copyright (C) 2013  itemis AG 
 * $Id$
 */

package org.jeegen.jee7.dbauth.dao;

import javax.ejb.Stateless;
import javax.persistence.TypedQuery;

import org.jeegen.jee7.dbauth.entities.AuthInfo;
import org.jeegen.jee7.util.Profiled;

@Stateless
@Profiled
public class UserDaoBean extends AbstractUserDaoBean
{
	public AuthInfo findAuthInfo(final String email)
	{
		TypedQuery<AuthInfo> query = em.createQuery("SELECT ai FROM AuthInfo ai WHERE ai.email = :email", AuthInfo.class);
		
		query.setParameter("email", email);
		
		return query.getSingleResult();
	}
}
