# Site settings
title: JEE Generator
email: info@jee-generator.de
description: > # this means to ignore newlines until "baseurl:"
  Die JEE-Generatoren sind in der Lage, eine komplette JEE-Web-Applikation (Java EE 6 oder Java EE 7) aus einem einfachen Modell zu generieren.
  Das Framework wurde mit Xtext realisiert und ist als Eclipse-Plugin verfügbar. Für Java EE 6 und Java EE 7 stehen getrennte Plugins zur Verfügung.

baseurl: "/Xtext" # the subpath of your site, e.g. /blog/

url: "http://jee-generator.de" # the base hostname & protocol for your site
encoding: UTF-8

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  #auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..4
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style

src:
  xtext: "https://github.com/eclipse/xtext/blob/v2.8.0"
  mwe: "https://github.com/eclipse/mwe/blob/v2.7.1"
  emf: "https://github.com/eclipse/emf/blob/R2_9_0"
  gef: "https://github.com/eclipse/gef/blob/master"

javadoc:
  utils6: "http://jee-generator.de/javadoc/jee6"
  utils7: "http://jee-generator.de/javadoc/jee7"
  eclipse-platform: "http://help.eclipse.org/luna/topic/org.eclipse.platform.doc.isv/reference/api"
  eclipse-jdt: "http://help.eclipse.org/luna/topic/org.eclipse.jdt.doc.isv/reference/api"
  java: "http://docs.oracle.com/javase/8/docs/api"
  javaee: "http://docs.oracle.com/javaee/5/api"
  junit: "http://junit.sourceforge.net/javadoc"
  guice: "https://google.github.io/guice/api-docs/latest/javadoc"