package generator;

import generator.AbstractWebsite;
import org.eclipse.xtend2.lib.StringConcatenation;

@SuppressWarnings("all")
public class Index extends AbstractWebsite {
  public String path() {
    return "index.html";
  }
  
  public CharSequence contents() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<!--Container-->");
    _builder.newLine();
    _builder.append("<br/><br/><br/>");
    _builder.newLine();
    _builder.append("<div id=\"header_wrapper\" class=\"container\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<div class=\"flexslider image-slider\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<div class=\"span5 slide\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<h2>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("Java Enterprise Development made <strong>Easy!</strong>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</h2>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<br />");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("Don\'t repeat yourself by implementing the same things ever and ever.");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("Use a simple DSL to generate an CRUD Prototype of your application,");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("change and extend it to your needs.");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<a href=\"download.html\" class=\"btn_download\"></a>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<div class=\"span6\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<div class=\"introduction\">");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<a href=\"#\"><img src=\"images/videoThumbnail.png\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("alt=\"image\" style=\"min-height: 420px; min-width: 580px;\"/></a>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<a href=\"http://www.youtube.com/watch?v=spnmScZUJHc\" rel=\"prettyPhoto\" title=\"Vorstellung des JEE6 Generators\" class=\"zoom zoom_icon\"></a>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("</div>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<div id=\"intro\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<div class=\"container\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<h1>Was ist der JEE6 Generator?</h1>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("Der JEE-6Generator ist in der Lage, eine komplette JEE6-Web-Applikation aus einem einfachen Modell zu generieren.<br />");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("Das Framework wurde mit Xtext realisiert und ist als Eclipse-Plugin verfügbar.");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("</div>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("<div id=\"features\">");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<div class=\"container\">");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<div class=\"row\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<div class=\"span12\">");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<br /> <br />");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<h1>A Selection Of Supported Features</h1>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<br />");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<div class=\"span4\">");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<div class=\"thumb\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<a href=\"#\"><img class=\"screenshot\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("src=\"images/feature2_syntax_coloring.png\" alt=\"Image\" /></a> <a");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("href=\"http://vimeo.com/12824833\" data-rel=\"prettyPhoto\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("title=\"Syntax Coloring\" class=\"zoom zoom_icon\"></a>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<h4>Syntax Coloring</h4>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("Out of the box, the editor supports <b>syntax coloring based");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("on the lexical structure</b> and the <b>semantic data</b> of your");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("files. Users are free to customize the highlighting and configure");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("their favorite styles.");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<div class=\"span4\">");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<div class=\"thumb\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<a href=\"#\"><img class=\"screenshot\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("src=\"images/feature2_content_assist.png\" alt=\"Image\" /></a> <a");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("href=\"http://vimeo.com/12824786\" data-rel=\"prettyPhoto\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("title=\"Content Assist\" class=\"zoom zoom_icon\"></a>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<h4>Content Assist</h4>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<p>An Xtext editor proposes valid code completions at any place");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("in the document, helping your users with the syntactical details");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("of your language.</p>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<div class=\"span4\">");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<div class=\"thumb\">");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("<a href=\"#\"><img class=\"screenshot\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("src=\"images/feature2_quick_fix.png\" alt=\"Image\" /></a> <a");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("href=\"http://vimeo.com/12824853\" data-rel=\"prettyPhoto\"");
    _builder.newLine();
    _builder.append("\t\t\t\t\t\t");
    _builder.append("title=\"Validation and Quick Fixes\" class=\"zoom zoom_icon\"></a>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<h4>Validation and Quick Fixes</h4>");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("<p>");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("Xtext has outstanding support for static analysis and validation");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("of your models. It has never been so easy to define constraints to");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("tackle <b>errors and warnings</b> in your code instantaneously.");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("With custom <b>quick fixes</b> you can correct these with a single");
    _builder.newLine();
    _builder.append("\t\t\t\t\t");
    _builder.append("keystroke.");
    _builder.newLine();
    _builder.append("\t\t\t\t");
    _builder.append("</p>");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</div>");
    _builder.newLine();
    _builder.append("</div>");
    _builder.newLine();
    return _builder;
  }
}
