
/*
 * Generated by Xtext/JEE7 Generator.
 * Copyright (C) 2014  itemis AG 
 * $Id$
 */

package org.jeegen.jee7.dbauth.beans;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.annotation.PostConstruct;
import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;
import javax.inject.Inject;

import org.jeegen.jee7.util.LogUtil;

/**
 * This class initializes the web application application.
 */
@ManagedBean(eager = true)
@ApplicationScoped
public class ApplicationController extends AbstractApplicationController {
	private static final long serialVersionUID = 1L;

	@Inject
	private Logger log;

	/**
	 * This method initializes this application. It logs the application banner.
	 */
	@PostConstruct
	public void init() {
		log.log(Level.FINE, ">init()");
		super.init();
		log.log(Level.CONFIG,
				"\n"
						+ LogUtil.banner("org.jeegen.jee7.dbauth.version",
								"DB-Auth"));
		log.log(Level.FINE, "<init()");
	}
}
