
/*
 * Generated by Xtext/JEE6 Generator.
 * Copyright (C) 2013  itemis AG 
 * $Id$
 */

package de.itemis.jee6.dbauth.entities;

import java.io.UnsupportedEncodingException;
import java.security.NoSuchAlgorithmException;

import javax.persistence.*;

import de.itemis.jee6.util.SHA1;

/**
 * This class implements the AuthInfo entity bean,
 */
@Entity
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@Table(name = "AuthInfo")
public class AuthInfo extends AbstractAuthInfo {
	private static final long serialVersionUID = 1L;
	private static final SHA1 sha1 = new SHA1();

	/**
	 * This method is a transient getter of the virtual property passwordUncoded.
	 *
	 * @return The computed value for property passwordUncoded.
	 */
	@Transient
	@Override
	public String getPasswordUncoded()
	{
		return getPassword();
	}
	
	public void setPasswordUncoded(final String password) throws NoSuchAlgorithmException, UnsupportedEncodingException
	{
		setPassword(sha1.encode(password));
	}
}
