/*
 * Generated by Xtext/JEE6 Generator.
 * $Id$
 */

package org.jeegen.faces.dao;

import javax.ejb.Stateless;
import javax.interceptor.Interceptors;

import org.jeegen.jee6.util.Profiler;

@Stateless
@Interceptors(Profiler.class)
public class AdminDaoBean extends AbstractAdminDaoBean
{
}
